# Site settings

url: "https://animalito.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

# baseurl: /

# Google tracking id to track your visitors

# google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

#############
# HTML Head #
#############

author: "Andrea Fernández Conde"
lang: "en"
title: "{ Andrea Fernández Conde }"
favicon: "/img/favicon.ico"
description: "Blog and website of Andrea Fernández, blogging mainly on data analysis. Opinions expressed are mine."
keywords: "andrea, fernandez, conde, animalito, animal, personal, jekyll, theme"

################
# Intro layout #
################

black-favicon: "/img/favicon.ico"
background-img: "../img/intro-big.jpg"
me-img: "/img/ns.JPG"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "Behold! I am the Animal!"
  - text: "Data lover, policy wonk, loves to dance."

########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
google-plus-share: True
linkedin-share: True
pinterest-share: True
vkontakte-share: True
disqus-shortname: "panossakkos"

###############
# Life Events #
###############

events:
  - image: "/img/career/spidertocat.png"
    date: "September 2013 - Today"
    description: "Animal-ing!"
  - image: "/img/career/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "animalsalvaje@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/feranimal"
  - title: "twitter"
    url: "https://twitter.com/feranimal"
  - title: "github"
    url: "https://github.com/animalito"
  - title: "linkedin"
    url: "https://mx.linkedin.com/in/andrea-fernandez-conde-ba0a8a47"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Exclusion list from the generated _site

exclude: ["LICENSE", "README", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems: [jekyll-paginate]
